### ISSUE TITLE
js_wp_editor( $settings ); must be loaded

### ISSUE THREAD

**Issue by tilight** [anteprimorac/js-wp-editor#2]
Hi,
i allways get the following warning:
js_wp_editor( $settings ); must be loaded
could you please explain me that i am doing wrong?

**Comment by anteprimorac** [comment]
Hi,
you can look at example in https://github.com/anteprimorac/js-wp-editor/blob/master/functions.php .

PS: currently this is not working with latest version of WordPress. I'm working on update.
