### ISSUE TITLE
Uncaught TypeError: switchEditors.switchto is not a function

### ISSUE THREAD

**Issue by jphase** [anteprimorac/js-wp-editor#3]
Hey there, just downloaded this and got it working pretty quickly, so thanks for the example! I am having an issue when trying to switch back and forth between Text/Visual tabs on the editor:

`Uncaught TypeError: switchEditors.switchto is not a function`

It doesn't look like switchto() is a method in the switchEditors object any longer. Do you happen to know what I might be able to change this to in order to fix the toggling between these two tabs?

**Comment by fortee** [comment]
This is due to changes to the core in Wordpress 4.3+.
You need replace
`onclick="switchEditors.switchto(this);"`
to
`data-wp-editor-id="'+current_id+'"`
in the js-wp-editor js file.

**Comment by danieliser** [comment]
Any reason this hasn't been merged in yet? Also possible to add a flag check for which version of WP is loaded and adding the correct output for each?

**Comment by anteprimorac** [comment]
@danieliser 
sorry, I should now have more time to spend on this lib.

**Comment by danieliser** [comment]
@anteprimorac Awesome, I just pitched a new JS based modal, tab & form rendering set of templates, models & functionality to the core team. If that gets any momentum I think this would be a great inclusion.

Question on the enqueuing, couldn't you just do wp_editor('', 'apid');
